name: Sync with Algolia search

on:
  push:
    paths:
      - content/**
      - .github/workflows/production-search-sync.yml
      - scripts/*

jobs:
  algolia-search-sync:
    name: Sync with Algolia Search
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - name: Build index
        run: node scripts/build-index.js

      - name: Show files
        run: ls -la && du -sh index.json

      - name: Upload Index
        env:
          ALGOLIA_SECRET: ${{ secrets.ALGOLIA_SECRET }}
        run: node scripts/upload-index.js

      - name: Get deleted files
        id: get-deleted-files
        uses: tj-actions/changed-files@v25
        with:
          # Refer https://github.com/tj-actions/changed-files#inputs
          # To know about following parameters
          json: true
          files: content/
          # to include the old names of the renamed files
          include_all_old_new_renamed_files: true
          # separater between two different files renamed
          old_new_files_separator: ":"
        # env:
          # HOME: "/actions-runner/_work/docs/docs"

      - name: Remove deleted files
        env:
          DELETED_FILES: ${{steps.get-deleted-files.outputs.deleted_files}}
          RENAMED_FILES: ${{steps.get-deleted-files.outputs.all_old_new_renamed_files}}
        run: node scripts/remove-records.js
